### PR TITLE
(doc) Fixed typo in about_boxstarter_bootstrapper

### PR DESCRIPTION
**Pull request by icnocop**
## Description Of Changes
Fixed a typo in about_boxstarter_bootstrapper.help.txt.
Changed `bust` to `must`.

## Motivation and Context
More readable documentation.

## Testing
N/A

## Change Types Made
* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.
* [x] Other: Documentation (non-breaking change)

## Related Issue
N/A (It's a trivial change)

## Change Checklist

* [ ] Requires a change to the documentation
* [x] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Review by flcdrg — APPROVED** [review]

**Comment by mwallner** [comment]
thanks for your contribution!

**Comment by gep13** [comment]
@mwallner this PR was targetting the `master` branch, when it ideally should have been targetting the develop branch.

**Comment by icnocop** [comment]
> @mwallner this PR was targetting the `master` branch, when it ideally should have been targetting the develop branch.

[CONTRIBUTING.md](https://github.com/chocolatey/boxstarter/blob/master/CONTRIBUTING.md) indicates:
> submit the pull request to the chocolatey/boxstarter repository against the master branch

Should [CONTRIBUTING.md](https://github.com/chocolatey/boxstarter/blob/master/CONTRIBUTING.md) be updated to reflect the differences between the `master` and `develop` branches?

**Comment by gep13** [comment]
@icnocop that is a great catch! Yes, that document needs to be updated. Is that something you would like to work on?

**Comment by icnocop** [comment]
> @icnocop that is a great catch! Yes, that document needs to be updated. Is that something you would like to work on?

I'm not sure I actually know how the `master` and `develop` branches are used in this repo, so I'm not exactly sure I'm the best person to update the documentation.

If it's just changing `master` to `develop`, then yes, I can do that, but it still won't answer why there are two branches, what each of them is for, and their relationship with each other.

**Comment by gep13** [comment]
This is a great point, and something that we likely need to document clearer somewhere, although I am not clear on exactly where the best place would be for that just now.

The Boxstarter GitHub repository uses the GitFlow Branching strategy - [you can find an article describes what this is here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

Any new work, unless otherwise discussed should target the `develop` branch.  Once things are ready, that work will be moved into the `master` branch for release.

In terms of the contributing.md file in this repository, I suspect that it might be as simple as switching reference from `master` to `develop` but there may be other areas that need to be updated. If you wanted to take a stab at this, I would happily review the changes.

Let me know if you have any questions.

**Pull request merged**
