### PR TITLE
(#508) Fix package iconUrl to be one that Chocolatey owns

### LINKED ISSUE #508: Update iconUrl to a domain owned directly have Chocolatey
## Is Your Feature Request Related To A Problem? Please describe.

Currently, the iconUrl for the Boxstarter Chocolatey packages uses:

```
https://cdn.rawgit.com/chocolatey/boxstarter/master/Web/Images/boxLogo_sm.png
```

During the recent v3.0.0 release, this URL failed to validate, since the entire Web directory was removed from the Boxstarter GitHub repository.  To prevent this from happening again, the iconUrl should be updated to a URL that is directory owned/maintained by Chocolatey.

## Describe The Solution. Why is it needed?

Suggestion would be to add the Boxstarter logo to this [repository](https://github.com/chocolatey/img) and the iconUrl would be updated to start with https://img.chocolatey.org

The old image likely needs to remain in the GitHub Repository, so that the icon for older package versions continues to work.

## Additional Context.

N/A

## Related Issues

N/A

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
Updated the package iconUrl to be from one that Chocolatey owns.

## Motivation and Context
Icon was pointing to somewhere we had no control over.

## Testing
N/A.

## Change Types Made

* [x] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

Fixes #508 

## Change Checklist

* [ ] Requires a change to the documentation
* [ ] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

### CODE REVIEW

**Review by gep13 — COMMENTED** [review]
This PR changes the icon from a 128x104 pixels image, to an image that is 70x61 pixels.

Was this intended?

**Comment by pauby** [comment]
Not really. I intended to just update the icon to point to the new image that we put onto img.chocolatey.org.

**Comment by pauby** [comment]
Updated it now and ready for re-review.

**Comment by gep13** [comment]
Looking at the new URL's, it looks like the icon URL has changed in the other direction now, i.e. the dimensions of the image is larger:

image

I have no objections to getting this merged in, I just wanted to point this out.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pauby thanks for getting these URL's fixed up.

**Pull request merged**
