### PR TITLE
Add Disable-AutoRebootWithLoggedOnUsers

### PR DESCRIPTION
**Pull request by dhilgarth**
Disables automatic reboots because of Windows Update when a user is logged on.

### CODE REVIEW

**Comment by dhilgarth** [comment]
Hey @mwrock, would you like me to create on PR per feature I am adding or should I add one PR with all of them?

**Comment by mwrock** [comment]
Yes please separate prs. Thanks!

**Comment by mwrock** [comment]
The unfortunate problem with this function is that boxstarter flips this registry setting off when it begins a run and then back on when it ends. See https://github.com/mwrock/boxstarter/blob/master/Boxstarter.Bootstrapper/Start-UpdateServices.ps1 and https://github.com/mwrock/boxstarter/blob/master/Boxstarter.Bootstrapper/Stop-UpdateServices.ps1.

Will need to change this up so that boxstarter honors what is set here without undoing it when done. Also need to have it backup the previous setting like it does for `NoAutoUpdate`.

Ideally, we would have one updates related function that would handle various settings like this one, the delivery one in your other PR and others as they are added.

**Comment by mwrock** [comment]
Closing this since it has been so long.

**Pull request closed without merging**
