### PR TITLE
(GH-336) Fix uninstall leftover shortcut

### PR DESCRIPTION
**Pull request by pauby**
Remove the start menu shortcut that is created by the Boxstarter.Chocolatey package.

### CODE REVIEW

**Comment by flcdrg** [comment]
I am happy to merge this - just checking do we prefer squash and merge or rebase ?

**Comment by pauby** [comment]
@flcdrg I was told a Merge commit previously. @gep13 Can you confirm?

**Comment by gep13** [comment]
@pauby @flcdrg personally, I normally always rebase PR's against the head of the target branch, and then merge into that branch (using --no-ff).  The latter is what you will get by pressing the bug green "Merge pull request" button.  I tend not to require a squashing of commits.

**Comment by gep13** [comment]
@pauby your changes have been merged, thanks for your contribution 👍

**Pull request merged**
